const regions = [
    { name: 'North East', value: 'north-east' },
    { name: 'North West', value: 'north-west' },
    { name: 'Yorkshire and The Humber', value: 'yorkshire-and-the-humber' },
    { name: 'East Midlands', value: 'east-midlands' },
    { name: 'West Midlands', value: 'west-midlands' },
    { name: 'East of England', value: 'east-of-england' },
    { name: 'London', value: 'london' },
    { name: 'South East', value: 'south-east' },
    { name: 'South West', value: 'south-west' }
];

const counties = [
    { label: 'Cambridgeshire', id: 'cambridgeshire', region: 'East of England' },
    { label: 'Cumbria', id: 'cumbria', region: 'North West' },
    { label: 'Derbyshire', id: 'derbyshire', region: 'East Midlands' },
    { label: 'Devon', id: 'devon', region: 'South West' },
    { label: 'East Sussex', id: 'east-sussex', region: 'South East' },
    { label: 'Essex', id: 'essex', region: 'East of England' },
    { label: 'Gloucestershire', id: 'gloucestershire', region: 'South West' },
    { label: 'Hampshire', id: 'hampshire', region: 'South East' },
    { label: 'Hertfordshire', id: 'hertfordshire', region: 'East of England' },
    { label: 'Kent', id: 'kent', region: 'South East' },
    { label: 'Lancashire', id: 'lancashire', region: 'North West' },
    { label: 'Leicestershire', id: 'leicestershire', region: 'East Midlands' },
    { label: 'Lincolnshire', id: 'lincolnshire', region: 'East Midlands' },
    { label: 'Norfolk', id: 'norfolk', region: 'East of England' },
    { label: 'North Yorkshire', id: 'north-yorkshire', region: 'Yorkshire and The Humber' },
    { label: 'Nottinghamshire', id: 'nottinghamshire', region: 'East Midlands' },
    { label: 'Oxfordshire', id: 'oxfordshire', region: 'South East' },
    { label: 'Somerset', id: 'somerset', region: 'South West' },
    { label: 'Staffordshire', id: 'staffordshire', region: 'West Midlands' },
    { label: 'Suffolk', id: 'suffolk', region: 'East of England' },
    { label: 'Surrey', id: 'surrey', region: 'South East' },
    { label: 'Warwickshire', id: 'warwickshire', region: 'West Midlands' },
    { label: 'West Sussex', id: 'west-sussex', region: 'South East' },
    { label: 'Worcestershire', id: 'worcestershire', region: 'West Midlands' },
    { label: 'Greater Manchester', id: 'greater-manchester', region: 'North West' },
    { label: 'Merseyside', id: 'merseyside', region: 'North West' },
    { label: 'South Yorkshire', id: 'south-yorkshire', region: 'Yorkshire and The Humber' },
    { label: 'Tyne and Wear', id: 'tyne-and-wear', region: 'North East' },
    { label: 'West Midlands', id: 'west-midlands', region: 'West Midlands' },
    { label: 'West Yorkshire', id: 'west-yorkshire', region: 'Yorkshire and The Humber' },
    { label: 'Inner London', id: 'inner-london', region: 'London' },
    { label: 'Outer London', id: 'outer-london', region: 'London' }
];

const places = [
    { code: 'E06000001', name: 'Hartlepool', county: '', region: 'North East', country: 'England' },
    { code: 'E06000002', name: 'Middlesbrough', county: '', region: 'North East', country: 'England' },
    { code: 'E06000003', name: 'Redcar and Cleveland', county: '', region: 'North East', country: 'England' },
    { code: 'E06000004', name: 'Stockton-on-Tees', county: '', region: 'North East', country: 'England' },
    { code: 'E06000005', name: 'Darlington', county: '', region: 'North East', country: 'England' },
    { code: 'E06000006', name: 'Halton', county: '', region: 'North West', country: 'England' },
    { code: 'E06000007', name: 'Warrington', county: '', region: 'North West', country: 'England' },
    { code: 'E06000008', name: 'Blackburn with Darwen', county: '', region: 'North West', country: 'England' },
    { code: 'E06000009', name: 'Blackpool', county: '', region: 'North West', country: 'England' },
    { code: 'E06000010', name: 'Kingston upon Hull, City of', county: '', region: 'Yorkshire and The Humber', country: 'England' },
    { code: 'E06000011', name: 'East Riding of Yorkshire', county: '', region: 'Yorkshire and The Humber', country: 'England' },
    { code: 'E06000012', name: 'North East Lincolnshire', county: '', region: 'Yorkshire and The Humber', country: 'England' },
    { code: 'E06000013', name: 'North Lincolnshire', county: '', region: 'Yorkshire and The Humber', country: 'England' },
    { code: 'E06000014', name: 'York', county: '', region: 'Yorkshire and The Humber', country: 'England' },
    { code: 'E06000015', name: 'Derby', county: '', region: 'East Midlands', country: 'England' },
    { code: 'E06000016', name: 'Leicester', county: '', region: 'East Midlands', country: 'England' },
    { code: 'E06000017', name: 'Rutland', county: '', region: 'East Midlands', country: 'England' },
    { code: 'E06000018', name: 'Nottingham', county: '', region: 'East Midlands', country: 'England' },
    { code: 'E06000019', name: 'Herefordshire, County of', county: '', region: 'West Midlands', country: 'England' },
    { code: 'E06000020', name: 'Telford and Wrekin', county: '', region: 'West Midlands', country: 'England' },
    { code: 'E06000021', name: 'Stoke-on-Trent', county: '', region: 'West Midlands', country: 'England' },
    { code: 'E06000022', name: 'Bath and North East Somerset', county: '', region: 'South West', country: 'England' },
    { code: 'E06000023', name: 'Bristol, City of', county: '', region: 'South West', country: 'England' },
    { code: 'E06000024', name: 'North Somerset', county: '', region: 'South West', country: 'England' },
    { code: 'E06000025', name: 'South Gloucestershire', county: '', region: 'South West', country: 'England' },
    { code: 'E06000026', name: 'Plymouth', county: '', region: 'South West', country: 'England' },
    { code: 'E06000027', name: 'Torbay', county: '', region: 'South West', country: 'England' },
    { code: 'E06000030', name: 'Swindon', county: '', region: 'South West', country: 'England' },
    { code: 'E06000031', name: 'Peterborough', county: '', region: 'East of England', country: 'England' },
    { code: 'E06000032', name: 'Luton', county: '', region: 'East of England', country: 'England' },
    { code: 'E06000033', name: 'Southend-on-Sea', county: '', region: 'East of England', country: 'England' },
    { code: 'E06000034', name: 'Thurrock', county: '', region: 'East of England', country: 'England' },
    { code: 'E06000035', name: 'Medway', county: '', region: 'South East', country: 'England' },
    { code: 'E06000036', name: 'Bracknell Forest', county: '', region: 'South East', country: 'England' },
    { code: 'E06000037', name: 'West Berkshire', county: '', region: 'South East', country: 'England' },
    { code: 'E06000038', name: 'Reading', county: '', region: 'South East', country: 'England' },
    { code: 'E06000039', name: 'Slough', county: '', region: 'South East', country: 'England' },
    { code: 'E06000040', name: 'Windsor and Maidenhead', county: '', region: 'South East', country: 'England' },
    { code: 'E06000041', name: 'Wokingham', county: '', region: 'South East', country: 'England' },
    { code: 'E06000042', name: 'Milton Keynes', county: '', region: 'South East', country: 'England' },
    { code: 'E06000043', name: 'Brighton and Hove', county: '', region: 'South East', country: 'England' },
    { code: 'E06000044', name: 'Portsmouth', county: '', region: 'South East', country: 'England' },
    { code: 'E06000045', name: 'Southampton', county: '', region: 'South East', country: 'England' },
    { code: 'E06000046', name: 'Isle of Wight', county: '', region: 'South East', country: 'England' },
    { code: 'E06000047', name: 'County Durham', county: '', region: 'North East', country: 'England' },
    { code: 'E06000049', name: 'Cheshire East', county: '', region: 'North West', country: 'England' },
    { code: 'E06000050', name: 'Cheshire West and Chester', county: '', region: 'North West', country: 'England' },
    { code: 'E06000051', name: 'Shropshire', county: '', region: 'West Midlands', country: 'England' },
    { code: 'E06000052', name: 'Cornwall', county: '', region: 'South West', country: 'England' },
    { code: 'E06000053', name: 'Isles of Scilly', county: '', region: 'South West', country: 'England' },
    { code: 'E06000054', name: 'Wiltshire', county: '', region: 'South West', country: 'England' },
    { code: 'E06000055', name: 'Bedford', county: '', region: 'East of England', country: 'England' },
    { code: 'E06000056', name: 'Central Bedfordshire', county: '', region: 'East of England', country: 'England' },
    { code: 'E06000057', name: 'Northumberland', county: '', region: 'North East', country: 'England' },
    { code: 'E06000058', name: 'Bournemouth, Christchurch and Poole', county: '', region: 'South West', country: 'England' },
    { code: 'E06000059', name: 'Dorset', county: '', region: 'South West', country: 'England' },
    { code: 'E06000060', name: 'Buckinghamshire', county: '', region: 'South East', country: 'England' },
    { code: 'E06000061', name: 'North Northamptonshire', county: '', region: 'East Midlands', country: 'England' },
    { code: 'E06000062', name: 'West Northamptonshire', county: '', region: 'East Midlands', country: 'England' },
    { code: 'E07000008', name: 'Cambridge', county: 'Cambridgeshire', region: 'East of England', country: 'England' },
    { code: 'E07000009', name: 'East Cambridgeshire', county: 'Cambridgeshire', region: 'East of England', country: 'England' },
    { code: 'E07000010', name: 'Fenland', county: 'Cambridgeshire', region: 'East of England', country: 'England' },
    { code: 'E07000011', name: 'Huntingdonshire', county: 'Cambridgeshire', region: 'East of England', country: 'England' },
    { code: 'E07000012', name: 'South Cambridgeshire', county: 'Cambridgeshire', region: 'East of England', country: 'England' },
    { code: 'E07000026', name: 'Allerdale', county: 'Cumbria', region: 'North West', country: 'England' },
    { code: 'E07000027', name: 'Barrow-in-Furness', county: 'Cumbria', region: 'North West', country: 'England' },
    { code: 'E07000028', name: 'Carlisle', county: 'Cumbria', region: 'North West', country: 'England' },
    { code: 'E07000029', name: 'Copeland', county: 'Cumbria', region: 'North West', country: 'England' },
    { code: 'E07000030', name: 'Eden', county: 'Cumbria', region: 'North West', country: 'England' },
    { code: 'E07000031', name: 'South Lakeland', county: 'Cumbria', region: 'North West', country: 'England' },
    { code: 'E07000032', name: 'Amber Valley', county: 'Derbyshire', region: 'East Midlands', country: 'England' },
    { code: 'E07000033', name: 'Bolsover', county: 'Derbyshire', region: 'East Midlands', country: 'England' },
    { code: 'E07000034', name: 'Chesterfield', county: 'Derbyshire', region: 'East Midlands', country: 'England' },
    { code: 'E07000035', name: 'Derbyshire Dales', county: 'Derbyshire', region: 'East Midlands', country: 'England' },
    { code: 'E07000036', name: 'Erewash', county: 'Derbyshire', region: 'East Midlands', country: 'England' },
    { code: 'E07000037', name: 'High Peak', county: 'Derbyshire', region: 'East Midlands', country: 'England' },
    { code: 'E07000038', name: 'North East Derbyshire', county: 'Derbyshire', region: 'East Midlands', country: 'England' },
    { code: 'E07000039', name: 'South Derbyshire', county: 'Derbyshire', region: 'East Midlands', country: 'England' },
    { code: 'E07000040', name: 'East Devon', county: 'Devon', region: 'South West', country: 'England' },
    { code: 'E07000041', name: 'Exeter', county: 'Devon', region: 'South West', country: 'England' },
    { code: 'E07000042', name: 'Mid Devon', county: 'Devon', region: 'South West', country: 'England' },
    { code: 'E07000043', name: 'North Devon', county: 'Devon', region: 'South West', country: 'England' },
    { code: 'E07000044', name: 'South Hams', county: 'Devon', region: 'South West', country: 'England' },
    { code: 'E07000045', name: 'Teignbridge', county: 'Devon', region: 'South West', country: 'England' },
    { code: 'E07000046', name: 'Torridge', county: 'Devon', region: 'South West', country: 'England' },
    { code: 'E07000047', name: 'West Devon', county: 'Devon', region: 'South West', country: 'England' },
    { code: 'E07000061', name: 'Eastbourne', county: 'East Sussex', region: 'South East', country: 'England' },
    { code: 'E07000062', name: 'Hastings', county: 'East Sussex', region: 'South East', country: 'England' },
    { code: 'E07000063', name: 'Lewes', county: 'East Sussex', region: 'South East', country: 'England' },
    { code: 'E07000064', name: 'Rother', county: 'East Sussex', region: 'South East', country: 'England' },
    { code: 'E07000065', name: 'Wealden', county: 'East Sussex', region: 'South East', country: 'England' },
    { code: 'E07000066', name: 'Basildon', county: 'Essex', region: 'East of England', country: 'England' },
    { code: 'E07000067', name: 'Braintree', county: 'Essex', region: 'East of England', country: 'England' },
    { code: 'E07000068', name: 'Brentwood', county: 'Essex', region: 'East of England', country: 'England' },
    { code: 'E07000069', name: 'Castle Point', county: 'Essex', region: 'East of England', country: 'England' },
    { code: 'E07000070', name: 'Chelmsford', county: 'Essex', region: 'East of England', country: 'England' },
    { code: 'E07000071', name: 'Colchester', county: 'Essex', region: 'East of England', country: 'England' },
    { code: 'E07000072', name: 'Epping Forest', county: 'Essex', region: 'East of England', country: 'England' },
    { code: 'E07000073', name: 'Harlow', county: 'Essex', region: 'East of England', country: 'England' },
    { code: 'E07000074', name: 'Maldon', county: 'Essex', region: 'East of England', country: 'England' },
    { code: 'E07000075', name: 'Rochford', county: 'Essex', region: 'East of England', country: 'England' },
    { code: 'E07000076', name: 'Tendring', county: 'Essex', region: 'East of England', country: 'England' },
    { code: 'E07000077', name: 'Uttlesford', county: 'Essex', region: 'East of England', country: 'England' },
    { code: 'E07000078', name: 'Cheltenham', county: 'Gloucestershire', region: 'South West', country: 'England' },
    { code: 'E07000079', name: 'Cotswold', county: 'Gloucestershire', region: 'South West', country: 'England' },
    { code: 'E07000080', name: 'Forest of Dean', county: 'Gloucestershire', region: 'South West', country: 'England' },
    { code: 'E07000081', name: 'Gloucester', county: 'Gloucestershire', region: 'South West', country: 'England' },
    { code: 'E07000082', name: 'Stroud', county: 'Gloucestershire', region: 'South West', country: 'England' },
    { code: 'E07000083', name: 'Tewkesbury', county: 'Gloucestershire', region: 'South West', country: 'England' },
    { code: 'E07000084', name: 'Basingstoke and Deane', county: 'Hampshire', region: 'South East', country: 'England' },
    { code: 'E07000085', name: 'East Hampshire', county: 'Hampshire', region: 'South East', country: 'England' },
    { code: 'E07000086', name: 'Eastleigh', county: 'Hampshire', region: 'South East', country: 'England' },
    { code: 'E07000087', name: 'Fareham', county: 'Hampshire', region: 'South East', country: 'England' },
    { code: 'E07000088', name: 'Gosport', county: 'Hampshire', region: 'South East', country: 'England' },
    { code: 'E07000089', name: 'Hart', county: 'Hampshire', region: 'South East', country: 'England' },
    { code: 'E07000090', name: 'Havant', county: 'Hampshire', region: 'South East', country: 'England' },
    { code: 'E07000091', name: 'New Forest', county: 'Hampshire', region: 'South East', country: 'England' },
    { code: 'E07000092', name: 'Rushmoor', county: 'Hampshire', region: 'South East', country: 'England' },
    { code: 'E07000093', name: 'Test Valley', county: 'Hampshire', region: 'South East', country: 'England' },
    { code: 'E07000094', name: 'Winchester', county: 'Hampshire', region: 'South East', country: 'England' },
    { code: 'E07000095', name: 'Broxbourne', county: 'Hertfordshire', region: 'East of England', country: 'England' },
    { code: 'E07000096', name: 'Dacorum', county: 'Hertfordshire', region: 'East of England', country: 'England' },
    { code: 'E07000098', name: 'Hertsmere', county: 'Hertfordshire', region: 'East of England', country: 'England' },
    { code: 'E07000099', name: 'North Hertfordshire', county: 'Hertfordshire', region: 'East of England', country: 'England' },
    { code: 'E07000102', name: 'Three Rivers', county: 'Hertfordshire', region: 'East of England', country: 'England' },
    { code: 'E07000103', name: 'Watford', county: 'Hertfordshire', region: 'East of England', country: 'England' },
    { code: 'E07000105', name: 'Ashford', county: 'Kent', region: 'South East', country: 'England' },
    { code: 'E07000106', name: 'Canterbury', county: 'Kent', region: 'South East', country: 'England' },
    { code: 'E07000107', name: 'Dartford', county: 'Kent', region: 'South East', country: 'England' },
    { code: 'E07000108', name: 'Dover', county: 'Kent', region: 'South East', country: 'England' },
    { code: 'E07000109', name: 'Gravesham', county: 'Kent', region: 'South East', country: 'England' },
    { code: 'E07000110', name: 'Maidstone', county: 'Kent', region: 'South East', country: 'England' },
    { code: 'E07000111', name: 'Sevenoaks', county: 'Kent', region: 'South East', country: 'England' },
    { code: 'E07000112', name: 'Folkestone and Hythe', county: 'Kent', region: 'South East', country: 'England' },
    { code: 'E07000113', name: 'Swale', county: 'Kent', region: 'South East', country: 'England' },
    { code: 'E07000114', name: 'Thanet', county: 'Kent', region: 'South East', country: 'England' },
    { code: 'E07000115', name: 'Tonbridge and Malling', county: 'Kent', region: 'South East', country: 'England' },
    { code: 'E07000116', name: 'Tunbridge Wells', county: 'Kent', region: 'South East', country: 'England' },
    { code: 'E07000117', name: 'Burnley', county: 'Lancashire', region: 'North West', country: 'England' },
    { code: 'E07000118', name: 'Chorley', county: 'Lancashire', region: 'North West', country: 'England' },
    { code: 'E07000119', name: 'Fylde', county: 'Lancashire', region: 'North West', country: 'England' },
    { code: 'E07000120', name: 'Hyndburn', county: 'Lancashire', region: 'North West', country: 'England' },
    { code: 'E07000121', name: 'Lancaster', county: 'Lancashire', region: 'North West', country: 'England' },
    { code: 'E07000122', name: 'Pendle', county: 'Lancashire', region: 'North West', country: 'England' },
    { code: 'E07000123', name: 'Preston', county: 'Lancashire', region: 'North West', country: 'England' },
    { code: 'E07000124', name: 'Ribble Valley', county: 'Lancashire', region: 'North West', country: 'England' },
    { code: 'E07000125', name: 'Rossendale', county: 'Lancashire', region: 'North West', country: 'England' },
    { code: 'E07000126', name: 'South Ribble', county: 'Lancashire', region: 'North West', country: 'England' },
    { code: 'E07000127', name: 'West Lancashire', county: 'Lancashire', region: 'North West', country: 'England' },
    { code: 'E07000128', name: 'Wyre', county: 'Lancashire', region: 'North West', country: 'England' },
    { code: 'E07000129', name: 'Blaby', county: 'Leicestershire', region: 'East Midlands', country: 'England' },
    { code: 'E07000130', name: 'Charnwood', county: 'Leicestershire', region: 'East Midlands', country: 'England' },
    { code: 'E07000131', name: 'Harborough', county: 'Leicestershire', region: 'East Midlands', country: 'England' },
    { code: 'E07000132', name: 'Hinckley and Bosworth', county: 'Leicestershire', region: 'East Midlands', country: 'England' },
    { code: 'E07000133', name: 'Melton', county: 'Leicestershire', region: 'East Midlands', country: 'England' },
    { code: 'E07000134', name: 'North West Leicestershire', county: 'Leicestershire', region: 'East Midlands', country: 'England' },
    { code: 'E07000135', name: 'Oadby and Wigston', county: 'Leicestershire', region: 'East Midlands', country: 'England' },
    { code: 'E07000136', name: 'Boston', county: 'Lincolnshire', region: 'East Midlands', country: 'England' },
    { code: 'E07000137', name: 'East Lindsey', county: 'Lincolnshire', region: 'East Midlands', country: 'England' },
    { code: 'E07000138', name: 'Lincoln', county: 'Lincolnshire', region: 'East Midlands', country: 'England' },
    { code: 'E07000139', name: 'North Kesteven', county: 'Lincolnshire', region: 'East Midlands', country: 'England' },
    { code: 'E07000140', name: 'South Holland', county: 'Lincolnshire', region: 'East Midlands', country: 'England' },
    { code: 'E07000141', name: 'South Kesteven', county: 'Lincolnshire', region: 'East Midlands', country: 'England' },
    { code: 'E07000142', name: 'West Lindsey', county: 'Lincolnshire', region: 'East Midlands', country: 'England' },
    { code: 'E07000143', name: 'Breckland', county: 'Norfolk', region: 'East of England', country: 'England' },
    { code: 'E07000144', name: 'Broadland', county: 'Norfolk', region: 'East of England', country: 'England' },
    { code: 'E07000145', name: 'Great Yarmouth', county: 'Norfolk', region: 'East of England', country: 'England' },
    { code: 'E07000146', name: 'King&rsquo;s Lynn and West Norfolk', county: 'Norfolk', region: 'East of England', country: 'England' },
    { code: 'E07000147', name: 'North Norfolk', county: 'Norfolk', region: 'East of England', country: 'England' },
    { code: 'E07000148', name: 'Norwich', county: 'Norfolk', region: 'East of England', country: 'England' },
    { code: 'E07000149', name: 'South Norfolk', county: 'Norfolk', region: 'East of England', country: 'England' },
    { code: 'E07000163', name: 'Craven', county: 'North Yorkshire', region: 'Yorkshire and The Humber', country: 'England' },
    { code: 'E07000164', name: 'Hambleton', county: 'North Yorkshire', region: 'Yorkshire and The Humber', country: 'England' },
    { code: 'E07000165', name: 'Harrogate', county: 'North Yorkshire', region: 'Yorkshire and The Humber', country: 'England' },
    { code: 'E07000166', name: 'Richmondshire', county: 'North Yorkshire', region: 'Yorkshire and The Humber', country: 'England' },
    { code: 'E07000167', name: 'Ryedale', county: 'North Yorkshire', region: 'Yorkshire and The Humber', country: 'England' },
    { code: 'E07000168', name: 'Scarborough', county: 'North Yorkshire', region: 'Yorkshire and The Humber', country: 'England' },
    { code: 'E07000169', name: 'Selby', county: 'North Yorkshire', region: 'Yorkshire and The Humber', country: 'England' },
    { code: 'E07000170', name: 'Ashfield', county: 'Nottinghamshire', region: 'East Midlands', country: 'England' },
    { code: 'E07000171', name: 'Bassetlaw', county: 'Nottinghamshire', region: 'East Midlands', country: 'England' },
    { code: 'E07000172', name: 'Broxtowe', county: 'Nottinghamshire', region: 'East Midlands', country: 'England' },
    { code: 'E07000173', name: 'Gedling', county: 'Nottinghamshire', region: 'East Midlands', country: 'England' },
    { code: 'E07000174', name: 'Mansfield', county: 'Nottinghamshire', region: 'East Midlands', country: 'England' },
    { code: 'E07000175', name: 'Newark and Sherwood', county: 'Nottinghamshire', region: 'East Midlands', country: 'England' },
    { code: 'E07000176', name: 'Rushcliffe', county: 'Nottinghamshire', region: 'East Midlands', country: 'England' },
    { code: 'E07000177', name: 'Cherwell', county: 'Oxfordshire', region: 'South East', country: 'England' },
    { code: 'E07000178', name: 'Oxford', county: 'Oxfordshire', region: 'South East', country: 'England' },
    { code: 'E07000179', name: 'South Oxfordshire', county: 'Oxfordshire', region: 'South East', country: 'England' },
    { code: 'E07000180', name: 'Vale of White Horse', county: 'Oxfordshire', region: 'South East', country: 'England' },
    { code: 'E07000181', name: 'West Oxfordshire', county: 'Oxfordshire', region: 'South East', country: 'England' },
    { code: 'E07000187', name: 'Mendip', county: 'Somerset', region: 'South West', country: 'England' },
    { code: 'E07000188', name: 'Sedgemoor', county: 'Somerset', region: 'South West', country: 'England' },
    { code: 'E07000189', name: 'South Somerset', county: 'Somerset', region: 'South West', country: 'England' },
    { code: 'E07000192', name: 'Cannock Chase', county: 'Staffordshire', region: 'West Midlands', country: 'England' },
    { code: 'E07000193', name: 'East Staffordshire', county: 'Staffordshire', region: 'West Midlands', country: 'England' },
    { code: 'E07000194', name: 'Lichfield', county: 'Staffordshire', region: 'West Midlands', country: 'England' },
    { code: 'E07000195', name: 'Newcastle-under-Lyme', county: 'Staffordshire', region: 'West Midlands', country: 'England' },
    { code: 'E07000196', name: 'South Staffordshire', county: 'Staffordshire', region: 'West Midlands', country: 'England' },
    { code: 'E07000197', name: 'Stafford', county: 'Staffordshire', region: 'West Midlands', country: 'England' },
    { code: 'E07000198', name: 'Staffordshire Moorlands', county: 'Staffordshire', region: 'West Midlands', country: 'England' },
    { code: 'E07000199', name: 'Tamworth', county: 'Staffordshire', region: 'West Midlands', country: 'England' },
    { code: 'E07000200', name: 'Babergh', county: 'Suffolk', region: 'East of England', country: 'England' },
    { code: 'E07000202', name: 'Ipswich', county: 'Suffolk', region: 'East of England', country: 'England' },
    { code: 'E07000203', name: 'Mid Suffolk', county: 'Suffolk', region: 'East of England', country: 'England' },
    { code: 'E07000207', name: 'Elmbridge', county: 'Surrey', region: 'South East', country: 'England' },
    { code: 'E07000208', name: 'Epsom and Ewell', county: 'Surrey', region: 'South East', country: 'England' },
    { code: 'E07000209', name: 'Guildford', county: 'Surrey', region: 'South East', country: 'England' },
    { code: 'E07000210', name: 'Mole Valley', county: 'Surrey', region: 'South East', country: 'England' },
    { code: 'E07000211', name: 'Reigate and Banstead', county: 'Surrey', region: 'South East', country: 'England' },
    { code: 'E07000212', name: 'Runnymede', county: 'Surrey', region: 'South East', country: 'England' },
    { code: 'E07000213', name: 'Spelthorne', county: 'Surrey', region: 'South East', country: 'England' },
    { code: 'E07000214', name: 'Surrey Heath', county: 'Surrey', region: 'South East', country: 'England' },
    { code: 'E07000215', name: 'Tandridge', county: 'Surrey', region: 'South East', country: 'England' },
    { code: 'E07000216', name: 'Waverley', county: 'Surrey', region: 'South East', country: 'England' },
    { code: 'E07000217', name: 'Woking', county: 'Surrey', region: 'South East', country: 'England' },
    { code: 'E07000218', name: 'North Warwickshire', county: 'Warwickshire', region: 'West Midlands', country: 'England' },
    { code: 'E07000219', name: 'Nuneaton and Bedworth', county: 'Warwickshire', region: 'West Midlands', country: 'England' },
    { code: 'E07000220', name: 'Rugby', county: 'Warwickshire', region: 'West Midlands', country: 'England' },
    { code: 'E07000221', name: 'Stratford-on-Avon', county: 'Warwickshire', region: 'West Midlands', country: 'England' },
    { code: 'E07000222', name: 'Warwick', county: 'Warwickshire', region: 'West Midlands', country: 'England' },
    { code: 'E07000223', name: 'Adur', county: 'West Sussex', region: 'South East', country: 'England' },
    { code: 'E07000224', name: 'Arun', county: 'West Sussex', region: 'South East', country: 'England' },
    { code: 'E07000225', name: 'Chichester', county: 'West Sussex', region: 'South East', country: 'England' },
    { code: 'E07000226', name: 'Crawley', county: 'West Sussex', region: 'South East', country: 'England' },
    { code: 'E07000227', name: 'Horsham', county: 'West Sussex', region: 'South East', country: 'England' },
    { code: 'E07000228', name: 'Mid Sussex', county: 'West Sussex', region: 'South East', country: 'England' },
    { code: 'E07000229', name: 'Worthing', county: 'West Sussex', region: 'South East', country: 'England' },
    { code: 'E07000234', name: 'Bromsgrove', county: 'Worcestershire', region: 'West Midlands', country: 'England' },
    { code: 'E07000235', name: 'Malvern Hills', county: 'Worcestershire', region: 'West Midlands', country: 'England' },
    { code: 'E07000236', name: 'Redditch', county: 'Worcestershire', region: 'West Midlands', country: 'England' },
    { code: 'E07000237', name: 'Worcester', county: 'Worcestershire', region: 'West Midlands', country: 'England' },
    { code: 'E07000238', name: 'Wychavon', county: 'Worcestershire', region: 'West Midlands', country: 'England' },
    { code: 'E07000239', name: 'Wyre Forest', county: 'Worcestershire', region: 'West Midlands', country: 'England' },
    { code: 'E07000240', name: 'St Albans', county: 'Hertfordshire', region: 'East of England', country: 'England' },
    { code: 'E07000241', name: 'Welwyn Hatfield', county: 'Hertfordshire', region: 'East of England', country: 'England' },
    { code: 'E07000242', name: 'East Hertfordshire', county: 'Hertfordshire', region: 'East of England', country: 'England' },
    { code: 'E07000243', name: 'Stevenage', county: 'Hertfordshire', region: 'East of England', country: 'England' },
    { code: 'E07000244', name: 'East Suffolk', county: 'Suffolk', region: 'East of England', country: 'England' },
    { code: 'E07000245', name: 'West Suffolk', county: 'Suffolk', region: 'East of England', country: 'England' },
    { code: 'E07000246', name: 'Somerset West and Taunton', county: 'Somerset', region: 'South West', country: 'England' },
    { code: 'E08000001', name: 'Bolton', county: 'Greater Manchester', region: 'North West', country: 'England' },
    { code: 'E08000002', name: 'Bury', county: 'Greater Manchester', region: 'North West', country: 'England' },
    { code: 'E08000003', name: 'Manchester', county: 'Greater Manchester', region: 'North West', country: 'England' },
    { code: 'E08000004', name: 'Oldham', county: 'Greater Manchester', region: 'North West', country: 'England' },
    { code: 'E08000005', name: 'Rochdale', county: 'Greater Manchester', region: 'North West', country: 'England' },
    { code: 'E08000006', name: 'Salford', county: 'Greater Manchester', region: 'North West', country: 'England' },
    { code: 'E08000007', name: 'Stockport', county: 'Greater Manchester', region: 'North West', country: 'England' },
    { code: 'E08000008', name: 'Tameside', county: 'Greater Manchester', region: 'North West', country: 'England' },
    { code: 'E08000009', name: 'Trafford', county: 'Greater Manchester', region: 'North West', country: 'England' },
    { code: 'E08000010', name: 'Wigan', county: 'Greater Manchester', region: 'North West', country: 'England' },
    { code: 'E08000011', name: 'Knowsley', county: 'Merseyside', region: 'North West', country: 'England' },
    { code: 'E08000012', name: 'Liverpool', county: 'Merseyside', region: 'North West', country: 'England' },
    { code: 'E08000013', name: 'St. Helens', county: 'Merseyside', region: 'North West', country: 'England' },
    { code: 'E08000014', name: 'Sefton', county: 'Merseyside', region: 'North West', country: 'England' },
    { code: 'E08000015', name: 'Wirral', county: 'Merseyside', region: 'North West', country: 'England' },
    { code: 'E08000016', name: 'Barnsley', county: 'South Yorkshire', region: 'Yorkshire and The Humber', country: 'England' },
    { code: 'E08000017', name: 'Doncaster', county: 'South Yorkshire', region: 'Yorkshire and The Humber', country: 'England' },
    { code: 'E08000018', name: 'Rotherham', county: 'South Yorkshire', region: 'Yorkshire and The Humber', country: 'England' },
    { code: 'E08000019', name: 'Sheffield', county: 'South Yorkshire', region: 'Yorkshire and The Humber', country: 'England' },
    { code: 'E08000021', name: 'Newcastle upon Tyne', county: 'Tyne and Wear', region: 'North East', country: 'England' },
    { code: 'E08000022', name: 'North Tyneside', county: 'Tyne and Wear', region: 'North East', country: 'England' },
    { code: 'E08000023', name: 'South Tyneside', county: 'Tyne and Wear', region: 'North East', country: 'England' },
    { code: 'E08000024', name: 'Sunderland', county: 'Tyne and Wear', region: 'North East', country: 'England' },
    { code: 'E08000025', name: 'Birmingham', county: 'West Midlands', region: 'West Midlands', country: 'England' },
    { code: 'E08000026', name: 'Coventry', county: 'West Midlands', region: 'West Midlands', country: 'England' },
    { code: 'E08000027', name: 'Dudley', county: 'West Midlands', region: 'West Midlands', country: 'England' },
    { code: 'E08000028', name: 'Sandwell', county: 'West Midlands', region: 'West Midlands', country: 'England' },
    { code: 'E08000029', name: 'Solihull', county: 'West Midlands', region: 'West Midlands', country: 'England' },
    { code: 'E08000030', name: 'Walsall', county: 'West Midlands', region: 'West Midlands', country: 'England' },
    { code: 'E08000031', name: 'Wolverhampton', county: 'West Midlands', region: 'West Midlands', country: 'England' },
    { code: 'E08000032', name: 'Bradford', county: 'West Yorkshire', region: 'Yorkshire and The Humber', country: 'England' },
    { code: 'E08000033', name: 'Calderdale', county: 'West Yorkshire', region: 'Yorkshire and The Humber', country: 'England' },
    { code: 'E08000034', name: 'Kirklees', county: 'West Yorkshire', region: 'Yorkshire and The Humber', country: 'England' },
    { code: 'E08000035', name: 'Leeds', county: 'West Yorkshire', region: 'Yorkshire and The Humber', country: 'England' },
    { code: 'E08000036', name: 'Wakefield', county: 'West Yorkshire', region: 'Yorkshire and The Humber', country: 'England' },
    { code: 'E08000037', name: 'Gateshead', county: 'Tyne and Wear', region: 'North East', country: 'England' },
    { code: 'E09000001', name: 'City of London', county: 'Inner London', region: 'London', country: 'England' },
    { code: 'E09000002', name: 'Barking and Dagenham', county: 'Outer London', region: 'London', country: 'England' },
    { code: 'E09000003', name: 'Barnet', county: 'Outer London', region: 'London', country: 'England' },
    { code: 'E09000004', name: 'Bexley', county: 'Outer London', region: 'London', country: 'England' },
    { code: 'E09000005', name: 'Brent', county: 'Outer London', region: 'London', country: 'England' },
    { code: 'E09000006', name: 'Bromley', county: 'Outer London', region: 'London', country: 'England' },
    { code: 'E09000007', name: 'Camden', county: 'Inner London', region: 'London', country: 'England' },
    { code: 'E09000008', name: 'Croydon', county: 'Outer London', region: 'London', country: 'England' },
    { code: 'E09000009', name: 'Ealing', county: 'Outer London', region: 'London', country: 'England' },
    { code: 'E09000010', name: 'Enfield', county: 'Outer London', region: 'London', country: 'England' },
    { code: 'E09000011', name: 'Greenwich', county: 'Outer London', region: 'London', country: 'England' },
    { code: 'E09000012', name: 'Hackney', county: 'Inner London', region: 'London', country: 'England' },
    { code: 'E09000013', name: 'Hammersmith and Fulham', county: 'Inner London', region: 'London', country: 'England' },
    { code: 'E09000014', name: 'Haringey', county: 'Inner London', region: 'London', country: 'England' },
    { code: 'E09000015', name: 'Harrow', county: 'Outer London', region: 'London', country: 'England' },
    { code: 'E09000016', name: 'Havering', county: 'Outer London', region: 'London', country: 'England' },
    { code: 'E09000017', name: 'Hillingdon', county: 'Outer London', region: 'London', country: 'England' },
    { code: 'E09000018', name: 'Hounslow', county: 'Outer London', region: 'London', country: 'England' },
    { code: 'E09000019', name: 'Islington', county: 'Inner London', region: 'London', country: 'England' },
    { code: 'E09000020', name: 'Kensington and Chelsea', county: 'Inner London', region: 'London', country: 'England' },
    { code: 'E09000021', name: 'Kingston upon Thames', county: 'Outer London', region: 'London', country: 'England' },
    { code: 'E09000022', name: 'Lambeth', county: 'Inner London', region: 'London', country: 'England' },
    { code: 'E09000023', name: 'Lewisham', county: 'Inner London', region: 'London', country: 'England' },
    { code: 'E09000024', name: 'Merton', county: 'Outer London', region: 'London', country: 'England' },
    { code: 'E09000025', name: 'Newham', county: 'Inner London', region: 'London', country: 'England' },
    { code: 'E09000026', name: 'Redbridge', county: 'Outer London', region: 'London', country: 'England' },
    { code: 'E09000027', name: 'Richmond upon Thames', county: 'Outer London', region: 'London', country: 'England' },
    { code: 'E09000028', name: 'Southwark', county: 'Inner London', region: 'London', country: 'England' },
    { code: 'E09000029', name: 'Sutton', county: 'Outer London', region: 'London', country: 'England' },
    { code: 'E09000030', name: 'Tower Hamlets', county: 'Inner London', region: 'London', country: 'England' },
    { code: 'E09000031', name: 'Waltham Forest', county: 'Outer London', region: 'London', country: 'England' },
    { code: 'E09000032', name: 'Wandsworth', county: 'Inner London', region: 'London', country: 'England' },
    { code: 'E09000033', name: 'Westminster', county: 'Inner London', region: 'London', country: 'England' },
    // { code: 'N09000001', name: 'Antrim and Newtownabbey', county: '', region: '', country: 'Northern Ireland' },
    // { code: 'N09000002', name: 'Armagh City, Banbridge and Craigavon', county: '', region: '', country: 'Northern Ireland' },
    // { code: 'N09000003', name: 'Belfast', county: '', region: '', country: 'Northern Ireland' },
    // { code: 'N09000004', name: 'Causeway Coast and Glens', county: '', region: '', country: 'Northern Ireland' },
    // { code: 'N09000005', name: 'Derry City and Strabane', county: '', region: '', country: 'Northern Ireland' },
    // { code: 'N09000006', name: 'Fermanagh and Omagh', county: '', region: '', country: 'Northern Ireland' },
    // { code: 'N09000007', name: 'Lisburn and Castlereagh', county: '', region: '', country: 'Northern Ireland' },
    // { code: 'N09000008', name: 'Mid and East Antrim', county: '', region: '', country: 'Northern Ireland' },
    // { code: 'N09000009', name: 'Mid Ulster', county: '', region: '', country: 'Northern Ireland' },
    // { code: 'N09000010', name: 'Newry, Mourne and Down', county: '', region: '', country: 'Northern Ireland' },
    // { code: 'N09000011', name: 'Ards and North Down', county: '', region: '', country: 'Northern Ireland' },
    // { code: 'S12000005', name: 'Clackmannanshire', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000006', name: 'Dumfries and Galloway', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000008', name: 'East Ayrshire', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000010', name: 'East Lothian', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000011', name: 'East Renfrewshire', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000013', name: 'Na h-Eileanan Siar', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000014', name: 'Falkirk', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000017', name: 'Highland', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000018', name: 'Inverclyde', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000019', name: 'Midlothian', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000020', name: 'Moray', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000021', name: 'North Ayrshire', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000023', name: 'Orkney Islands', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000026', name: 'Scottish Borders', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000027', name: 'Shetland Islands', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000028', name: 'South Ayrshire', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000029', name: 'South Lanarkshire', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000030', name: 'Stirling', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000033', name: 'Aberdeen City', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000034', name: 'Aberdeenshire', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000035', name: 'Argyll and Bute', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000036', name: 'City of Edinburgh', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000038', name: 'Renfrewshire', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000039', name: 'West Dunbartonshire', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000040', name: 'West Lothian', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000041', name: 'Angus', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000042', name: 'Dundee City', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000045', name: 'East Dunbartonshire', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000047', name: 'Fife', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000048', name: 'Perth and Kinross', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000049', name: 'Glasgow City', county: '', region: '', country: 'Scotland' },
    // { code: 'S12000050', name: 'North Lanarkshire', county: '', region: '', country: 'Scotland' },
    { code: 'W06000001', name: 'Isle of Anglesey', county: '', region: '', country: 'Wales' },
    { code: 'W06000002', name: 'Gwynedd', county: '', region: '', country: 'Wales' },
    { code: 'W06000003', name: 'Conwy', county: '', region: '', country: 'Wales' },
    { code: 'W06000004', name: 'Denbighshire', county: '', region: '', country: 'Wales' },
    { code: 'W06000005', name: 'Flintshire', county: '', region: '', country: 'Wales' },
    { code: 'W06000006', name: 'Wrexham', county: '', region: '', country: 'Wales' },
    { code: 'W06000008', name: 'Ceredigion', county: '', region: '', country: 'Wales' },
    { code: 'W06000009', name: 'Pembrokeshire', county: '', region: '', country: 'Wales' },
    { code: 'W06000010', name: 'Carmarthenshire', county: '', region: '', country: 'Wales' },
    { code: 'W06000011', name: 'Swansea', county: '', region: '', country: 'Wales' },
    { code: 'W06000012', name: 'Neath Port Talbot', county: '', region: '', country: 'Wales' },
    { code: 'W06000013', name: 'Bridgend', county: '', region: '', country: 'Wales' },
    { code: 'W06000014', name: 'Vale of Glamorgan', county: '', region: '', country: 'Wales' },
    { code: 'W06000015', name: 'Cardiff', county: '', region: '', country: 'Wales' },
    { code: 'W06000016', name: 'Rhondda Cynon Taf', county: '', region: '', country: 'Wales' },
    { code: 'W06000018', name: 'Caerphilly', county: '', region: '', country: 'Wales' },
    { code: 'W06000019', name: 'Blaenau Gwent', county: '', region: '', country: 'Wales' },
    { code: 'W06000020', name: 'Torfaen', county: '', region: '', country: 'Wales' },
    { code: 'W06000021', name: 'Monmouthshire', county: '', region: '', country: 'Wales' },
    { code: 'W06000022', name: 'Newport', county: '', region: '', country: 'Wales' },
    { code: 'W06000023', name: 'Powys', county: '', region: '', country: 'Wales' },
    { code: 'W06000024', name: 'Merthyr Tydfil', county: '', region: '', country: 'Wales' }
];